In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

import sys
sys.path.append("../src")
from OmiScraper import OmiScraper

In [2]:
dt = pd.read_csv("../Datasets/Real_Listing_FCO_Cleaned.csv")
omi_dt = pd.read_csv("../Datasets/OMI_FCO_Cleaned.csv")

In [3]:
dt.head(3)

,Area,Street,ID_Listing,Price,Surface sqm,Rooms,Bathrooms,External Features,External Surface sqm,Floor,Levels,Parking,Furnished,Condition,Listing Status,Construction Year,Floor1
0,Isola Sacra (FCO) - Via Trincea delle Frasche,Passo Buole,Iso_Buo_1,296000,130,4,3,B,40.0,3.0,3,O,N,2,available,2019.0,3.0
1,Isola Sacra (FCO) - Via Trincea delle Frasche,Trincea delle Frasche,Iso_Fra_2,197000,60,2,1,T,NaN,1.0,2,O,N,1,available,2025.0,1.0
2,Isola Sacra (FCO) - Via Trincea delle Frasche,Trincea delle Frasche,Iso_Fra_3,285000,125,4,3,B,NaN,1.0,2,B,N,1,available,2026.0,1.0

In [4]:
omi_dt

,Area,Property Type,Sale Price €/sqm Min,Sale Price €/sqm Max,Rent Price €/sqm per Month Min,Rent Price €/sqm per Month Max,Province,Municipality,OMI Zone,OMI Zone Code,Cadastral Microzone,Dominant Property Type
0,Isola Sacra,Abitazioni civili,1850,2750,8,12.0,Rome,Fiumicino,Periferica/ISOLA SACRA-DARSENA (VIA DEL FARO),D1,0,Abitazioni Civili
1,Isola Sacra,Abitazioni di tipo economico,1750,2600,7,10.0,Rome,Fiumicino,Periferica/ISOLA SACRA-DARSENA (VIA DEL FARO),D1,0,Abitazioni Civili
2,Isola Sacra,Box,1100,1650,4,6.0,Rome,Fiumicino,Periferica/ISOLA SACRA-DARSENA (VIA DEL FARO),D1,0,Abitazioni Civili
3,Isola Sacra,Ville e Villini,2100,3000,8,11.5,Rome,Fiumicino,Periferica/ISOLA SACRA-DARSENA (VIA DEL FARO),D1,0,Abitazioni Civili

---

In [6]:
fco_estate_1 = pd.DataFrame([{
    "Area": "Isola Sacra (FCO) - Via Trincea delle Frasche",
    "Street": "Trincea delle Frasche",
    "ID_Listing": "Iso_Fra_101",
    "Price": np.nan,
    "Surface sqm": 109,
    "Rooms": 6,
    "Bathrooms": 1,
    "External Features": "T + G",
    "External Surface sqm": 150,
    "Floor": 1,
    "Levels": 2,
    "Parking": "O",
    "Furnished": "Y",
    "Condition": 2,
    "Listing Status": "available",
    "Construction": 1993,
    "Floor1": 1
}])

In [7]:
fco_estate_2 = pd.DataFrame([{
    "Area": "Isola Sacra (FCO) - Via Trincea delle Frasche",
    "Street": "Trincea delle Frasche",
    "ID_Listing": "Iso_Fra_102",
    "Price": np.nan,
    "Surface sqm": 109,
    "Rooms": 6,
    "Bathrooms": 1,
    "External Features": "T + G",
    "External Surface sqm": 500,
    "Floor": 2,
    "Levels": 2,
    "Parking": "O",
    "Furnished": "Y",
    "Condition": 2,
    "Listing Status": "available",
    "Construction": 1993,
    "Floor1": 2
}])

In [8]:
fco_estate_total = pd.DataFrame([{
    "Area": "Isola Sacra (FCO) - Via Trincea delle Frasche",
    "Street": "Trincea delle Frasche",
    "ID_Listing": "Iso_Fra_103",
    "Price": np.nan,
    "Surface sqm": 218,
    "Rooms": 12,
    "Bathrooms": 2,
    "External Features": "T + G",
    "External Surface sqm": 650,
    "Floor": np.nan,
    "Levels": 2,
    "Parking": "O",
    "Furnished": "Y",
    "Condition": 2,
    "Listing Status": "available",
    "Construction": 1993,
    "Floor1": "whole building"
}])

In [9]:
dt_estate_fco = pd.concat([fco_estate_1, fco_estate_2, fco_estate_total], ignore_index = True)
dt_estate_fco

,Area,Street,ID_Listing,Price,Surface sqm,Rooms,Bathrooms,External Features,External Surface sqm,Floor,Levels,Parking,Furnished,Condition,Listing Status,Construction,Floor1
0,Isola Sacra (FCO) - Via Trincea delle Frasche,Trincea delle Frasche,Iso_Fra_101,NaN,109,6,1,T + G,150,1.0,2,O,Y,2,available,1993,1
1,Isola Sacra (FCO) - Via Trincea delle Frasche,Trincea delle Frasche,Iso_Fra_102,NaN,109,6,1,T + G,500,2.0,2,O,Y,2,available,1993,2
2,Isola Sacra (FCO) - Via Trincea delle Frasche,Trincea delle Frasche,Iso_Fra_103,NaN,218,12,2,T + G,650,NaN,2,O,Y,2,available,1993,whole building

In [18]:
dt_estate_fco

,Area,Street,ID_Listing,Price,Surface sqm,Rooms,Bathrooms,External Features,External Surface sqm,Floor,Levels,Parking,Furnished,Condition,Listing Status,Construction,Floor1
0,Isola Sacra (FCO) - Via Trincea delle Frasche,Trincea delle Frasche,Iso_Fra_101,NaN,109,6,1,T + G,150,1.0,2,O,Y,2,available,1993,1
1,Isola Sacra (FCO) - Via Trincea delle Frasche,Trincea delle Frasche,Iso_Fra_102,NaN,109,6,1,T + G,500,2.0,2,O,Y,2,available,1993,2
2,Isola Sacra (FCO) - Via Trincea delle Frasche,Trincea delle Frasche,Iso_Fra_103,NaN,218,12,2,T + G,650,NaN,2,O,Y,2,available,1993,whole building

---

In [21]:
dt["Sale Price euro/sqm"] = dt["Price"]/dt["Surface sqm"]
cols = dt.columns.to_list()
cols.remove("Sale Price euro/sqm")
cols.insert(5, "Sale Price euro/sqm")
dt = dt[cols]
dt.head(2)

,Area,Street,ID_Listing,Price,Surface sqm,Sale Price euro/sqm,Rooms,Bathrooms,External Features,External Surface sqm,Floor,Levels,Parking,Furnished,Condition,Listing Status,Construction Year,Floor1
0,Isola Sacra (FCO) - Via Trincea delle Frasche,Passo Buole,Iso_Buo_1,296000,130,2276.923077,4,3,B,40.0,3.0,3,O,N,2,available,2019.0,3.0
1,Isola Sacra (FCO) - Via Trincea delle Frasche,Trincea delle Frasche,Iso_Fra_2,197000,60,3283.333333,2,1,T,NaN,1.0,2,O,N,1,available,2025.0,1.0

## 1. OMI evaluation

In [ ]:
omi_dt.drop(2, axis = 0, inplace = True)

In [32]:
omi_dt = omi_dt.reset_index(drop = True)
omi_dt

,Area,Property Type,Sale Price €/sqm Min,Sale Price €/sqm Max,Rent Price €/sqm per Month Min,Rent Price €/sqm per Month Max,Province,Municipality,OMI Zone,OMI Zone Code,Cadastral Microzone,Dominant Property Type
0,Isola Sacra,Abitazioni civili,1850,2750,8,12.0,Rome,Fiumicino,Periferica/ISOLA SACRA-DARSENA (VIA DEL FARO),D1,0,Abitazioni Civili
1,Isola Sacra,Abitazioni di tipo economico,1750,2600,7,10.0,Rome,Fiumicino,Periferica/ISOLA SACRA-DARSENA (VIA DEL FARO),D1,0,Abitazioni Civili
2,Isola Sacra,Ville e Villini,2100,3000,8,11.5,Rome,Fiumicino,Periferica/ISOLA SACRA-DARSENA (VIA DEL FARO),D1,0,Abitazioni Civili

In [36]:
for i in range(len(dt)):
    min_price_internal_1st_floor = dt.iloc[i,3] * 109
    max_price_internal_1st_floor = dt.iloc[i, 4] * 109
    
    min_price_external_1st_floor = dt.iloc[i, 3] * 150 *0.1
    max_price_external_1st_floor = dt.iloc[i, 4] * 150 *0.1
    
    min_total_price_1st_floor = min_price_internal_1st_floor + min_price_external_1st_floor
    max_total_price_1st_floor = max_price_internal_1st_floor + max_price_external_1st_floor

    print()

    min_price_internal_2nd_floor = dt.iloc[i,3] * 109
    max_price_internal_2nd_floor = dt.iloc[i, 4] * 109
    min_price_external_2nd_floor = dt.iloc[i, 3] * 500 *0.1
    max_price_external_2nd_floor = dt.iloc[i, 4] * 500 *0.1
    min_total_price_2nd_floor = min_price_internal_2nd_floor + min_price_external_2nd_floor
    max_total_price_2nd_floor = max_price_internal_2nd_floor + max_price_external_2nd_floor

## 2. Real Listing Evaluation

In [57]:
dt["Sale Price euro/sqm"].describe().to_frame()

       Sale Price euro/sqm
count            49.000000
mean           2692.840787
std             738.650643
min            1147.500000
25%            2222.222222
50%            2490.000000
75%            3250.000000
max            4545.454545

In [65]:
dt["Sale Price euro/sqm"].median()

2490.0

In [85]:
omi_dt

,Area,Property Type,Sale Price €/sqm Min,Sale Price €/sqm Max,Rent Price €/sqm per Month Min,Rent Price €/sqm per Month Max,Province,Municipality,OMI Zone,OMI Zone Code,Cadastral Microzone,Dominant Property Type
0,Isola Sacra,Abitazioni civili,1850,2750,8,12.0,Rome,Fiumicino,Periferica/ISOLA SACRA-DARSENA (VIA DEL FARO),D1,0,Abitazioni Civili
1,Isola Sacra,Abitazioni di tipo economico,1750,2600,7,10.0,Rome,Fiumicino,Periferica/ISOLA SACRA-DARSENA (VIA DEL FARO),D1,0,Abitazioni Civili
2,Isola Sacra,Box,1100,1650,4,6.0,Rome,Fiumicino,Periferica/ISOLA SACRA-DARSENA (VIA DEL FARO),D1,0,Abitazioni Civili
3,Isola Sacra,Ville e Villini,2100,3000,8,11.5,Rome,Fiumicino,Periferica/ISOLA SACRA-DARSENA (VIA DEL FARO),D1,0,Abitazioni Civili

In [ ]:
dt.loc[0, "Sale Price €/sqm Min"] +

In [87]:
dt.head(0)

Empty DataFrame
Columns: [Area, Street, ID_Listing, Price, Surface sqm, Sale Price euro/sqm, Rooms, Bathrooms, External Features, External Surface sqm, Floor, Levels, Parking, Furnished, Condition, Listing Status, Construction Year, Floor1]
Index: []

In [97]:
dt["External Features"].str.contains("G", na=False).value_counts()

External Features
True     26
False    23
Name: count, dtype: int64